### ISSUE TITLE
No data.arc found

### ISSUE THREAD

**Issue by KMSBishly** [ultimate-research/UltimateModManager#13]
So I have the correct folders and files in place (I believe) but it says that there is no data.arc even though there is. 
![image](https://user-images.githubusercontent.com/76638106/103163462-1ca18e80-47b3-11eb-87e2-a415acf342c5.png)

![image](https://user-images.githubusercontent.com/76638106/103163464-20cdac00-47b3-11eb-80c4-13bb9fd96336.png)

![image](https://user-images.githubusercontent.com/76638106/103163468-23c89c80-47b3-11eb-9869-8236bda255ca.png)

**Comment by Genwald** [comment]
Full yuzu support is in UMM's beta release for now. Also, if you want to avoid moving the data.arc after every mod install, you must set your "load" path in yuzu to `[path to virtual sd]/yuzu/load/` which would be something like `C:/Users/[user name]/AppData/Roaming/yuzu/sdmc/yuzu/load/` by default.
What you have looks right, but I see you aren't using the beta and I'm not sure if you've set your "load" path.

**Comment by xully** [comment]
my UMM is doing the same thing, i have correct paths for everything and im in beta version (im on yuzu)

**Comment by Genwald** [comment]
If you are using a very new version of Yuzu, I would assume this to be a totally separate issue and should probably be opened as such.   
I assume since yuzu-emu/yuzu#6472 looks to be merged, but yuzu-emu/yuzu#6471 has not yet, UMM's method of detecting Yuzu no longer works, and it is detected as atmosphere instead. I do not think that `sd:/atmosphere/contents/01006A800016E000/romfs/` can be set as a location for romfs layeredfs due to Yuzu's different layeredfs layout compared to atmosphere. So fixing this would require detecting Yuzu in a different way, but since yuzu-emu/yuzu#6471 will presumably be merged soon, I'll just recommend using an older version of Yuzu for now.

**Comment by xully** [comment]
How would I get an older version? When it auto updates itself?

**Comment by Genwald** [comment]
I'm not very familiar with Yuzu. I would assume that you can disable the auto-updater. If you can not, talk to Yuzu's devs about it.

**Comment by Genwald** [comment]
Did you try googling how to do this? I just did and found a solution quickly. Either way, any issues you have using Yuzu which are unrelated to UMM do not belong in an issue on UMM's GitHub page.
