### ISSUE TITLE
Smash Ultimate crashes on boot up

### ISSUE THREAD

**Issue by Themainman1360** [ultimate-research/UltimateModManager#14]
I'm having issues booting smash, I've gotten some errors where it mentions data.arc doesn't match but it would still play so I ignored it. I tried to untinstall all mods and delete the manager itself but now it doesn't boot at all, reinstalled smash and now I'm redumping the data.arc. How does one properly uninstall this?

**Comment by Genwald** [comment]
>  I've gotten some errors where it mentions data.arc doesn't match

Yes, that was fixed in the latest version. The warning was not accurate on previous versions.

UMM works by modifying your data.arc. None of its changes to the game will be there after re-dumping or removing the data.arc. If you still have crashes after that, UMM is likely not the issue.

Mods never change your actual install of the game, so you should never need to reinstall. You can hold L while launching smash to disable layeredfs for that launch of the game. This will disable all mods that are not loaded by custom sysmodules (like saltyNX). So if you run into an issue like this again, you can simply hold L to get back to playing if you don't want to immediately fix the issue.
