### ISSUE TITLE
Mod installation problems with yuzu

### ISSUE THREAD

**Issue by Wololo-o** [ultimate-research/UltimateModManager#19]
(Sorry for my bad english)

With the last Yuzu version, when I click on "Dump romfs in sdmc", the `data.arc` file is created in an `sdmc/atmosphere/` subdirectory.

It is not detected by Ultimate Mod Manager when it is in `sdmc/yuzu/load/[game_id]/UMM/romfs`

After getting the `data.arc` file (in the atmosphere subdirectory), I can install mods but if I launch the game, quit the game, install other mods and launch the game again, the mods I installed after the first launch aren't installed.

**Comment by Genwald** [comment]
Due to changes in Yuzu, Yuzu is now mimicking atmosphere in new way, which caused UMM to detect it as atmosphere, but it should also be mimicking how atmosphere loads layeredfs mods. So just put the data.arc where it would go if you were using atmosphere (which is likely where the option you mentioned dumped it to), don't try and replace the file from both locations at once, make sure Yuzu is up to date, and all should be fine. 
Anyway, UMM's behavior has not changed, Yuzu's has, and as I understand it Yuzu intends to mimic atmosphere's behavior here. So this doesn't sound like a UMM issue to me and the issues section should not be used for user support. If you can confirm that Yuzu has changed in a way that breaks UMM and that they do not intend to fix this, then you can open a feature request issue asking for support on newer versions.
