### ISSUE TITLE
Can't Uninstalll Modsssss!!! Beware!

### ISSUE THREAD

**Issue by KamiSquadX** [ultimate-research/UltimateModManager#7]
Great program and tool but a big issue is when you want to revert back to vanilla, its almost impossible. Maybe i accidentally moved the "backup" files somewhere "safe" on my pc and lost it... Or the backup function is broken or something. Even deleting the smash ultimate digital copy and redownloading from eshop STILL HAS MODS ENABLED! 
I'll keep trying to uninstall but for now its ridiculous...

**Comment by jugeeya** [comment]
You must've somehow moved the backups folder so it couldn't restore them. If you want to really go back to vanilla, just redump using the Data Arc Dumper in UMM.

**Comment by KamiSquadX** [comment]
I tried that already. It still increases load times unnecessarily...

**Comment by Genwald** [comment]
Issues with increased load times are almost certainly not the fault of this program. It is most likely just your SD card having slow read speeds, but this program just edits a file, it doesn't run along side the game. 
Also please keep to one topic per issue. This issue is about uninstalling mods, not load times. Discussion of load times is off topic here.
